"""Evaluate AstroCELLECT center completeness by reference magnitude.

This script mirrors the completeness side of
``lsst_pipeline/utils/run_cutout_magnitude_experiment.py``: reference catalog
fluxes are converted to instrumental magnitudes, predicted centers are matched
one-to-one to reference centers, and completeness is reported in magnitude bins.

It can also overlay existing LSST/SAM aggregate CSVs generated by the LSST
pipeline script.  That avoids importing LSST stack modules in this conda
environment; run the LSST pipeline in its own environment first, then pass its
``magnitude_metrics_aggregate.csv`` here.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import torch
from astropy.table import Table
from torch.utils.data import DataLoader
from tqdm import tqdm

from astro_cellect2d import AstroUNet2D, FusedEncoderMultiBandAstroCELLECT2D, MultiBandAstroCELLECT2D
from astro_train_eval import (
    AstroCutoutDataset,
    CutoutRecord,
    collate_cutouts,
    detect_centers,
    detect_centers_with_en,
    detect_centers_with_ex_link,
    discover_cutout_records,
)


DEFAULT_LSST_AGGREGATE = Path(
    "/home/chenzunhao/segment-anything/lsst_pipeline/output/"
    "cutout_magnitude_experiment_grid/irg_64_denoised/magnitude_metrics_aggregate.csv"
)


def _expand(path: str | Path) -> Path:
    return Path(path).expanduser().resolve()


def _finite_col(table: Table, names: Sequence[str]) -> Optional[np.ndarray]:
    for name in names:
        if name in table.colnames:
            vals = np.asarray(table[name], dtype=np.float32)
            if np.isfinite(vals).any():
                return vals
    return None


def _source_mask(table: Table, source_filter: str) -> np.ndarray:
    n = len(table)
    if source_filter == "all":
        return np.ones(n, dtype=bool)
    parent = np.asarray(table["parent"], dtype=np.int64) if "parent" in table.colnames else np.zeros(n, dtype=np.int64)
    if source_filter == "parent":
        return parent == 0
    if "deblend_nChild" in table.colnames:
        nchild = np.asarray(table["deblend_nChild"], dtype=np.int64)
    elif "nChild" in table.colnames:
        nchild = np.asarray(table["nChild"], dtype=np.int64)
    else:
        raise KeyError(f"source_filter={source_filter!r} requires deblend_nChild or nChild")
    leaf = nchild == 0
    if source_filter == "nchild0":
        return leaf
    if source_filter == "leaf_child":
        return leaf & (parent != 0)
    raise ValueError(f"Unknown source_filter: {source_filter}")


def _choose_flux_col(table: Table, preferred: str, fallbacks: Sequence[str]) -> str:
    for name in (preferred, *fallbacks):
        if name in {"", "auto", "none", "None"}:
            continue
        if name in table.colnames:
            return name
    raise KeyError(f"none of these flux columns exists: {(preferred, *fallbacks)}")


def _flux_to_mag(flux: np.ndarray, zero_point: float) -> np.ndarray:
    flux = np.asarray(flux, dtype=np.float64)
    mag = np.full(flux.shape, np.nan, dtype=np.float64)
    good = np.isfinite(flux) & (flux > 0)
    mag[good] = float(zero_point) - 2.5 * np.log10(flux[good])
    return mag


def load_reference_sources(
    record: CutoutRecord,
    *,
    image_shape: Tuple[int, int],
    source_filter: str,
    flux_col: str,
    mag_zero_point: float,
    require_finite_shape: bool,
) -> Dict[str, np.ndarray | str]:
    """Load GT centers and magnitudes with the same filters as training/eval."""

    table = Table.read(record.meas_path, hdu=1)
    x = _finite_col(
        table,
        (
            "centroid_local_x",
            "base_SdssShape_x",
            "base_SdssCentroid_x",
            "base_NaiveCentroid_x",
            "deblend_psfCenter_x",
        ),
    )
    y = _finite_col(
        table,
        (
            "centroid_local_y",
            "base_SdssShape_y",
            "base_SdssCentroid_y",
            "base_NaiveCentroid_y",
            "deblend_psfCenter_y",
        ),
    )
    if x is None or y is None:
        raise ValueError(f"No usable centroid columns found in {record.meas_path}")
    if "centroid_local_x" not in table.colnames:
        x = x - float(record.x0)
    if "centroid_local_y" not in table.colnames:
        y = y - float(record.y0)

    h, w = image_shape
    valid = np.isfinite(x) & np.isfinite(y) & (x >= 0) & (x < w) & (y >= 0) & (y < h)
    valid &= _source_mask(table, source_filter)

    if require_finite_shape:
        xx = _finite_col(table, ("base_SdssShape_xx", "ext_shapeHSM_HsmSourceMoments_xx"))
        yy = _finite_col(table, ("base_SdssShape_yy", "ext_shapeHSM_HsmSourceMoments_yy"))
        xy = _finite_col(table, ("base_SdssShape_xy", "ext_shapeHSM_HsmSourceMoments_xy"))
        if xx is not None and yy is not None and xy is not None:
            valid &= np.isfinite(xx) & np.isfinite(yy) & np.isfinite(xy)

    chosen_flux_col = _choose_flux_col(
        table,
        flux_col,
        ("modelfit_CModel_instFlux", "base_PsfFlux_instFlux", "base_SdssShape_instFlux"),
    )
    flux = np.asarray(table[chosen_flux_col], dtype=np.float64)
    centers = np.stack([x[valid], y[valid]], axis=1).astype(np.float32)
    mag = _flux_to_mag(flux[valid], mag_zero_point)
    return {"centers": centers, "mag": mag, "flux_col": chosen_flux_col}


def match_reference_to_predictions(
    ref_xy: np.ndarray,
    pred_xy: np.ndarray,
    *,
    radius_px: float,
) -> np.ndarray:
    """Greedy nearest-neighbor matching; return boolean mask over references."""

    ref_xy = np.asarray(ref_xy, dtype=np.float32)
    pred_xy = np.asarray(pred_xy, dtype=np.float32)
    ref_used = np.zeros(ref_xy.shape[0], dtype=bool)
    if ref_xy.size == 0 or pred_xy.size == 0:
        return ref_used
    dist = np.sqrt(((ref_xy[:, None, :] - pred_xy[None, :, :]) ** 2).sum(axis=2))
    ref_idx, pred_idx = np.nonzero(dist <= float(radius_px))
    order = np.argsort(dist[ref_idx, pred_idx], kind="stable")
    pred_used = np.zeros(pred_xy.shape[0], dtype=bool)
    for item in order:
        ri = int(ref_idx[item])
        pi = int(pred_idx[item])
        if ref_used[ri] or pred_used[pi]:
            continue
        ref_used[ri] = True
        pred_used[pi] = True
    return ref_used


def magnitude_bins(mag_min: float, mag_max: float, bin_size: float) -> List[Tuple[float, float, float]]:
    edges = np.arange(float(mag_min), float(mag_max) + float(bin_size) * 0.5, float(bin_size))
    return [(float(lo), float(hi), float(0.5 * (lo + hi))) for lo, hi in zip(edges[:-1], edges[1:])]


def bin_rows_for_cutout(
    *,
    cutout: str,
    method: str,
    mag: np.ndarray,
    ref_used: np.ndarray,
    bins: Sequence[Tuple[float, float, float]],
    flux_col: str,
) -> List[dict]:
    rows: List[dict] = []
    for lo, hi, center in bins:
        in_bin = np.isfinite(mag) & (mag >= lo) & (mag < hi)
        total = int(np.count_nonzero(in_bin))
        matched = int(np.count_nonzero(in_bin & ref_used))
        rows.append(
            {
                "cutout": cutout,
                "method": method,
                "mag_left": lo,
                "mag_right": hi,
                "mag_center": center,
                "reference_flux_col": flux_col,
                "reference_total": total,
                "reference_matched": matched,
                "completeness": matched / total if total else math.nan,
            }
        )
    return rows


def aggregate_rows(rows: Sequence[dict]) -> List[dict]:
    grouped: Dict[Tuple[str, float, float], dict] = {}
    for row in rows:
        key = (str(row["method"]), float(row["mag_left"]), float(row["mag_right"]))
        item = grouped.setdefault(
            key,
            {
                "cutout": "",
                "method": row["method"],
                "mag_left": float(row["mag_left"]),
                "mag_right": float(row["mag_right"]),
                "mag_center": float(row["mag_center"]),
                "reference_flux_col": row.get("reference_flux_col", ""),
                "reference_total": 0,
                "reference_matched": 0,
            },
        )
        item["reference_total"] += int(row["reference_total"])
        item["reference_matched"] += int(row["reference_matched"])
    out = []
    for item in grouped.values():
        total = int(item["reference_total"])
        matched = int(item["reference_matched"])
        item["completeness"] = matched / total if total else math.nan
        out.append(item)
    return sorted(out, key=lambda row: (str(row["method"]), float(row["mag_left"])))


def load_lsst_aggregate(path: Path, *, label: Optional[str], mag_min: float, mag_max: float) -> List[dict]:
    rows: List[dict] = []
    if not path.exists():
        raise FileNotFoundError(path)
    with path.open(newline="") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            lo = float(row["mag_left"])
            hi = float(row["mag_right"])
            if not np.isfinite(lo) or not np.isfinite(hi):
                continue
            if lo < mag_min or hi > mag_max:
                continue
            method = label or row.get("method", "lsst")
            rows.append(
                {
                    "cutout": "",
                    "method": method,
                    "mag_left": lo,
                    "mag_right": hi,
                    "mag_center": float(row["mag_center"]),
                    "reference_flux_col": row.get("reference_flux_col", ""),
                    "reference_total": int(float(row["reference_total"])),
                    "reference_matched": int(float(row["reference_matched"])),
                    "completeness": float(row["completeness"]) if row.get("completeness") else math.nan,
                }
            )
    return rows


def write_csv(path: Path, rows: Sequence[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = [
        "cutout",
        "method",
        "mag_left",
        "mag_right",
        "mag_center",
        "reference_flux_col",
        "reference_total",
        "reference_matched",
        "completeness",
    ]
    with path.open("w", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def plot_completeness(path: Path, rows: Sequence[dict], *, title: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    methods = sorted({str(row["method"]) for row in rows})
    preferred = [name for name in ("astro", "lsst") if name in methods]
    methods = preferred + [name for name in methods if name not in preferred]

    fig, ax = plt.subplots(figsize=(8.8, 5.2), constrained_layout=True)
    for method in methods:
        method_rows = [row for row in rows if str(row["method"]) == method]
        method_rows = sorted(method_rows, key=lambda row: float(row["mag_center"]))
        x = np.array([row["mag_center"] for row in method_rows], dtype=float)
        y = np.array([row["completeness"] for row in method_rows], dtype=float)
        ax.plot(x, y, marker="o", linewidth=1.9, label=method)
    ax.set_title(title)
    ax.set_xlabel("reference instrumental magnitude")
    ax.set_ylabel("completeness")
    ax.set_ylim(-0.03, 1.03)
    ax.grid(alpha=0.25)
    ax.spines[["top", "right"]].set_visible(False)
    if methods:
        ax.legend(frameon=False)
    fig.savefig(path, dpi=180)
    plt.close(fig)


def _ordered_methods(rows: Sequence[dict]) -> List[str]:
    methods = sorted({str(row["method"]) for row in rows})
    preferred = [name for name in ("astro", "lsst") if name in methods]
    return preferred + [name for name in methods if name not in preferred]


def filter_rows_by_mag(rows: Sequence[dict], *, mag_min: float, mag_max: float) -> List[dict]:
    return [
        row
        for row in rows
        if float(row["mag_left"]) >= float(mag_min) and float(row["mag_right"]) <= float(mag_max)
    ]


def plot_count_bars(path: Path, rows: Sequence[dict], *, title: str) -> None:
    """Plot GT denominator and true-positive detections per magnitude bin."""

    path.parent.mkdir(parents=True, exist_ok=True)
    bins = sorted({(float(row["mag_left"]), float(row["mag_right"]), float(row["mag_center"])) for row in rows})
    methods = _ordered_methods(rows)
    if not bins:
        return

    x = np.arange(len(bins), dtype=float)
    labels = [f"{lo:g}-{hi:g}" for lo, hi, _ in bins]
    gt_counts = []
    for lo, hi, _ in bins:
        bin_rows = [row for row in rows if float(row["mag_left"]) == lo and float(row["mag_right"]) == hi]
        gt_counts.append(max((int(row["reference_total"]) for row in bin_rows), default=0))

    fig_width = max(10.0, min(18.0, 0.62 * len(bins)))
    fig, ax = plt.subplots(figsize=(fig_width, 5.6), constrained_layout=True)
    ax.bar(x, gt_counts, width=0.86, color="#d8dadd", edgecolor="#aeb3b8", linewidth=0.6, label="GT")

    if methods:
        total_width = min(0.66, 0.18 * len(methods) + 0.08)
        bar_width = total_width / max(len(methods), 1)
        start = -0.5 * total_width + 0.5 * bar_width
        colors = plt.rcParams["axes.prop_cycle"].by_key().get("color", ["#1f77b4", "#ff7f0e"])
        for method_idx, method in enumerate(methods):
            values = []
            for lo, hi, _ in bins:
                row = next(
                    (
                        item
                        for item in rows
                        if str(item["method"]) == method
                        and float(item["mag_left"]) == lo
                        and float(item["mag_right"]) == hi
                    ),
                    None,
                )
                values.append(int(row["reference_matched"]) if row is not None else 0)
            ax.bar(
                x + start + method_idx * bar_width,
                values,
                width=bar_width,
                color=colors[method_idx % len(colors)],
                alpha=0.88,
                label=f"{method} detected",
            )

    ax.set_title(title)
    ax.set_xlabel("reference instrumental magnitude bin")
    ax.set_ylabel("source count")
    ax.set_xticks(x)
    ax.set_xticklabels(labels, rotation=45, ha="right")
    ax.grid(axis="y", alpha=0.25)
    ax.spines[["top", "right"]].set_visible(False)
    ax.legend(frameon=False)
    fig.savefig(path, dpi=180)
    plt.close(fig)


def _flatten_per_band_outputs(outputs: Dict[str, torch.Tensor]) -> Dict[str, torch.Tensor]:
    if outputs["seg_logits"].ndim != 5:
        return outputs
    return {key: value.reshape(value.shape[0] * value.shape[1], *value.shape[2:]) for key, value in outputs.items()}


def build_model(args: argparse.Namespace, checkpoint: dict, device: torch.device) -> torch.nn.Module:
    ckpt_args = checkpoint.get("args", {}) if isinstance(checkpoint, dict) else {}
    embedding_dim = int(ckpt_args.get("embedding_dim", args.embedding_dim))
    base_channels = int(ckpt_args.get("base_channels", args.base_channels))
    model_variant = checkpoint.get("model_variant") if isinstance(checkpoint, dict) else None
    if model_variant in ("per_band", "fused_encoder"):
        model_cls = MultiBandAstroCELLECT2D if model_variant == "per_band" else FusedEncoderMultiBandAstroCELLECT2D
        model = model_cls(
            num_bands=len(args.bands),
            seg_classes=3,
            confidence_levels=5,
            embedding_dim=embedding_dim,
            base_channels=base_channels,
            shape_channels=3,
            candidate_count=int(ckpt_args.get("matcher_candidate_count", args.matcher_candidate_count)),
            shape_feature_dim=6,
        ).to(device)
    else:
        model = AstroUNet2D(
            in_channels=len(args.bands),
            seg_classes=3,
            confidence_levels=5,
            embedding_dim=embedding_dim,
            base_channels=base_channels,
            shape_channels=3,
        ).to(device)
    state = checkpoint["model"] if isinstance(checkpoint, dict) and "model" in checkpoint else checkpoint
    model.load_state_dict(state)
    if hasattr(model, "EX") and hasattr(model, "EN") and isinstance(checkpoint, dict):
        if checkpoint.get("EX") is not None:
            model.EX.load_state_dict(checkpoint["EX"])
        if checkpoint.get("EN") is not None:
            model.EN.load_state_dict(checkpoint["EN"])
    model.eval()
    return model


@torch.no_grad()
def evaluate_astro(args: argparse.Namespace) -> Tuple[List[dict], dict]:
    device = torch.device(args.device if args.device == "cpu" or torch.cuda.is_available() else "cpu")
    checkpoint = torch.load(args.checkpoint, map_location=device)
    model = build_model(args, checkpoint, device)

    records = discover_cutout_records(
        args.root,
        reference_dir=args.reference_dir,
        cutout_dir=args.cutout_dir,
        band_reference_root=args.band_reference_root,
        bands=args.bands,
        max_records=args.max_records,
    )
    if args.record_names:
        keep = set(args.record_names)
        records = [record for record in records if record.name in keep]
    elif args.use_checkpoint_val and isinstance(checkpoint, dict) and checkpoint.get("val_record_names"):
        keep = set(checkpoint["val_record_names"])
        records = [record for record in records if record.name in keep]
    if not records:
        raise RuntimeError("No records selected for magnitude completeness evaluation")

    dataset = AstroCutoutDataset(
        records,
        fits_hdu=args.fits_hdu,
        confidence_levels=5,
        ellipse_sigma=args.ellipse_sigma,
        core_radius=args.core_radius,
        shape_source=args.shape_source,
        source_filter=args.source_filter,
        targets_dir=args.targets_dir if args.targets_dir and args.targets_dir.exists() else None,
        image_cache_dir=args.image_cache_dir,
        augment=False,
    )
    loader = DataLoader(
        dataset,
        batch_size=args.batch_size,
        shuffle=False,
        num_workers=args.num_workers,
        collate_fn=collate_cutouts,
    )
    record_by_name = {record.name: record for record in records}
    bins = magnitude_bins(args.mag_min, args.mag_max, args.bin_size)
    match_radius = args.match_radius_arcsec / args.pixel_scale

    rows: List[dict] = []
    total_ref = total_matched = total_pred = 0
    for batch in tqdm(loader, desc="astro magnitude", leave=False):
        image = batch["image"].to(device=device, dtype=torch.float32)
        outputs = model(image)
        if args.use_ex_link_postprocess and outputs["seg_logits"].ndim == 5 and hasattr(model, "EX"):
            pred_list, _components = detect_centers_with_ex_link(
                model,
                outputs,
                threshold=args.confidence_threshold,
                nms_radius=args.nms_radius,
                confidence_score=args.confidence_score,
                match_radius=match_radius,
                candidate_count=args.matcher_candidate_count,
                ex_threshold=args.ex_link_threshold,
                use_en_postprocess=args.use_en_postprocess,
                en_threshold=args.en_postprocess_threshold,
            )
        elif args.use_en_postprocess and hasattr(model, "EN"):
            pred_list = detect_centers_with_en(
                model,
                outputs,
                threshold=args.confidence_threshold,
                nms_radius=args.nms_radius,
                confidence_score=args.confidence_score,
                match_radius=match_radius,
                candidate_count=args.matcher_candidate_count,
                en_threshold=args.en_postprocess_threshold,
            )
        elif outputs["seg_logits"].ndim == 5:
            pred_list = detect_centers(
                _flatten_per_band_outputs(outputs),
                threshold=args.confidence_threshold,
                nms_radius=args.nms_radius,
                confidence_score=args.confidence_score,
            )
        else:
            pred_list = detect_centers(
                outputs,
                threshold=args.confidence_threshold,
                nms_radius=args.nms_radius,
                confidence_score=args.confidence_score,
            )
        per_band_prediction = outputs["seg_logits"].ndim == 5 and not (
            args.use_ex_link_postprocess and hasattr(model, "EX")
        )
        if per_band_prediction:
            expected = len(batch["name"]) * len(args.bands)
            if len(pred_list) != expected:
                raise RuntimeError(
                    f"prediction list length {len(pred_list)} does not match batch*bands {expected}; "
                    "per-band magnitude completeness expects one prediction set per cutout per band"
                )
            prediction_items = []
            for batch_idx, name in enumerate(batch["name"]):
                record = record_by_name[str(name)]
                for band_idx, band_name in enumerate(args.bands):
                    meas_path = (
                        record.band_meas_paths[band_idx]
                        if record.band_meas_paths and band_idx < len(record.band_meas_paths)
                        else record.meas_path
                    )
                    band_record = CutoutRecord(
                        name=record.name,
                        image_paths=record.image_paths,
                        meas_path=meas_path,
                        x0=record.x0,
                        y0=record.y0,
                    )
                    prediction_items.append(
                        (
                            f"{name}:{band_name}",
                            f"{args.astro_label}-{band_name}",
                            pred_list[batch_idx * len(args.bands) + band_idx],
                            batch["image"][batch_idx],
                            band_record,
                        )
                    )
        else:
            if len(pred_list) != len(batch["name"]):
                raise RuntimeError(
                    f"prediction list length {len(pred_list)} does not match batch size {len(batch['name'])}"
                )
            prediction_items = [
                (str(name), args.astro_label, pred_xy, image_tensor, record_by_name[str(name)])
                for name, pred_xy, image_tensor in zip(batch["name"], pred_list, batch["image"])
            ]

        for name, method, pred_xy, image_tensor, record in prediction_items:
            h, w = int(image_tensor.shape[-2]), int(image_tensor.shape[-1])
            ref = load_reference_sources(
                record,
                image_shape=(h, w),
                source_filter=args.source_filter,
                flux_col=args.ref_flux_col,
                mag_zero_point=args.mag_zero_point,
                require_finite_shape=args.require_finite_shape,
            )
            ref_xy = ref["centers"]  # type: ignore[assignment]
            mag = ref["mag"]  # type: ignore[assignment]
            ref_used = match_reference_to_predictions(ref_xy, pred_xy, radius_px=match_radius)  # type: ignore[arg-type]
            rows.extend(
                bin_rows_for_cutout(
                    cutout=str(name),
                    method=str(method),
                    mag=mag,  # type: ignore[arg-type]
                    ref_used=ref_used,
                    bins=bins,
                    flux_col=str(ref["flux_col"]),
                )
            )
            total_ref += int(ref_used.shape[0])
            total_matched += int(ref_used.sum())
            total_pred += int(pred_xy.shape[0])

    summary = {
        "records": len(records),
        "reference_total": total_ref,
        "prediction_total": total_pred,
        "matched_total": total_matched,
        "completeness": total_matched / total_ref if total_ref else math.nan,
        "precision": total_matched / total_pred if total_pred else math.nan,
        "match_radius_pix": match_radius,
        "match_radius_arcsec": args.match_radius_arcsec,
    }
    return rows, summary


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Magnitude-binned completeness for AstroCELLECT with optional LSST overlay.")
    parser.add_argument("--root", type=Path, default=Path("./output/hsc_astro_preprocessed"))
    parser.add_argument("--reference-dir", type=Path, default=None)
    parser.add_argument("--cutout-dir", type=Path, default=None)
    parser.add_argument("--band-reference-root", type=Path, default=None)
    parser.add_argument("--targets-dir", type=Path, default=None)
    parser.add_argument("--image-cache-dir", type=Path, default=None)
    parser.add_argument("--checkpoint", type=Path, default=Path("./output/astro_hsc_i_cellect_conf/best.pt"))
    parser.add_argument("--out-dir", type=Path, default=Path("./output/astro_magnitude_completeness"))
    parser.add_argument("--bands", nargs="+", default=("HSC-I",))
    parser.add_argument("--fits-hdu", type=int, default=1)
    parser.add_argument("--batch-size", type=int, default=4)
    parser.add_argument("--num-workers", type=int, default=0)
    parser.add_argument("--max-records", type=int, default=None)
    parser.add_argument("--record-names", nargs="*", default=None)
    parser.add_argument("--use-checkpoint-val", action="store_true", help="Evaluate only val_record_names stored in the checkpoint run_config/checkpoint.")
    parser.add_argument("--source-filter", choices=("nchild0", "all", "parent", "leaf_child"), default="nchild0")
    parser.add_argument(
        "--require-finite-shape",
        action="store_true",
        help="Also require finite shape moments in the reference denominator. Disabled by default to match LSST magnitude metrics.",
    )
    parser.add_argument("--shape-source", choices=("kron", "sdss", "circular_kron"), default="sdss")
    parser.add_argument("--ellipse-sigma", type=float, default=2.0)
    parser.add_argument("--core-radius", type=int, default=2)
    parser.add_argument("--confidence-threshold", type=float, default=0.0)
    parser.add_argument("--confidence-score", choices=("cellect", "raw", "ordinal_prob"), default="cellect")
    parser.add_argument("--nms-radius", type=int, default=1)
    parser.add_argument("--use-en-postprocess", action="store_true")
    parser.add_argument("--en-postprocess-threshold", type=float, default=0.6)
    parser.add_argument("--use-ex-link-postprocess", action="store_true")
    parser.add_argument("--ex-link-threshold", type=float, default=0.5)
    parser.add_argument("--matcher-candidate-count", type=int, default=5)
    parser.add_argument("--match-radius-arcsec", type=float, default=0.5)
    parser.add_argument("--pixel-scale", type=float, default=0.168)
    parser.add_argument("--ref-flux-col", default="base_PsfFlux_instFlux")
    parser.add_argument("--mag-zero-point", type=float, default=27.0)
    parser.add_argument("--mag-min", type=float, default=18.0)
    parser.add_argument("--mag-max", type=float, default=30.0)
    parser.add_argument("--bin-size", type=float, default=1.0)
    parser.add_argument("--completeness-plot-min", type=float, default=23.0)
    parser.add_argument("--astro-label", default="astro")
    parser.add_argument("--lsst-aggregate-csv", type=Path, default=DEFAULT_LSST_AGGREGATE)
    parser.add_argument("--lsst-label", default="lsst")
    parser.add_argument("--no-lsst-overlay", action="store_true")
    parser.add_argument("--base-channels", type=int, default=32)
    parser.add_argument("--embedding-dim", type=int, default=64)
    parser.add_argument("--device", default="cuda" if torch.cuda.is_available() else "cpu")
    return parser


def main() -> None:
    args = build_arg_parser().parse_args()
    args.root = _expand(args.root)
    args.checkpoint = _expand(args.checkpoint)
    args.out_dir = _expand(args.out_dir)
    args.reference_dir = _expand(args.reference_dir) if args.reference_dir else None
    args.cutout_dir = _expand(args.cutout_dir) if args.cutout_dir else None
    args.band_reference_root = _expand(args.band_reference_root) if args.band_reference_root else None
    args.targets_dir = _expand(args.targets_dir) if args.targets_dir else args.root / "targets"
    args.image_cache_dir = _expand(args.image_cache_dir) if args.image_cache_dir else None
    args.lsst_aggregate_csv = _expand(args.lsst_aggregate_csv) if args.lsst_aggregate_csv else None
    args.out_dir.mkdir(parents=True, exist_ok=True)

    per_cutout_rows, summary = evaluate_astro(args)
    astro_aggregate = aggregate_rows(per_cutout_rows)
    combined = list(astro_aggregate)
    if not args.no_lsst_overlay and args.lsst_aggregate_csv is not None and args.lsst_aggregate_csv.exists():
        combined.extend(
            load_lsst_aggregate(
                args.lsst_aggregate_csv,
                label=args.lsst_label,
                mag_min=args.mag_min,
                mag_max=args.mag_max,
            )
        )

    write_csv(args.out_dir / "astro_magnitude_completeness_per_cutout.csv", per_cutout_rows)
    write_csv(args.out_dir / "astro_magnitude_completeness_aggregate.csv", astro_aggregate)
    write_csv(args.out_dir / "magnitude_completeness_comparison.csv", combined)
    plot_completeness(
        args.out_dir / "magnitude_completeness_comparison.png",
        combined,
        title=f"Completeness by reference magnitude ({args.mag_min:g}-{args.mag_max:g})",
    )
    plot_count_bars(
        args.out_dir / "magnitude_counts_gt_detected.png",
        combined,
        title=f"GT and detected sources by magnitude ({args.mag_min:g}-{args.mag_max:g})",
    )
    completeness_focus = filter_rows_by_mag(
        combined,
        mag_min=args.completeness_plot_min,
        mag_max=args.mag_max,
    )
    plot_completeness(
        args.out_dir / "magnitude_completeness_23_30.png",
        completeness_focus,
        title=f"Completeness by reference magnitude ({args.completeness_plot_min:g}-{args.mag_max:g})",
    )
    metadata = {
        "args": {key: str(value) if isinstance(value, Path) else value for key, value in vars(args).items()},
        "astro_summary": summary,
        "lsst_aggregate_csv_used": str(args.lsst_aggregate_csv)
        if not args.no_lsst_overlay and args.lsst_aggregate_csv and args.lsst_aggregate_csv.exists()
        else None,
    }
    (args.out_dir / "magnitude_completeness_metadata.json").write_text(json.dumps(metadata, indent=2), encoding="utf-8")
    print(json.dumps(summary, indent=2))
    print(f"wrote {args.out_dir / 'magnitude_completeness_comparison.png'}")
    print(f"wrote {args.out_dir / 'magnitude_counts_gt_detected.png'}")
    print(f"wrote {args.out_dir / 'magnitude_completeness_23_30.png'}")
    print(f"wrote {args.out_dir / 'magnitude_completeness_comparison.csv'}")


if __name__ == "__main__":
    main()
